server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8081
spring:
  application:
    name: my-base-web
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 100MB #限制文件上传大小为100M
      max-request-size: 100MB
      enabled: true #开启文件上传

